### ISSUE TITLE
Needs editing for grammar, spelling, and typos.  I have an edit prepared but I can't push it up to github

### ISSUE THREAD

**Issue by Terry-Thompson** [learn-co-students/positioning-elements-with-css-v-000#4]

**Comment by ladybando** [comment]
I completed a spelling and grammar fix and submitted a pull request.

**Comment by Terry-Thompson** [comment]
Thanks.  You ROCK!

**Comment by drakeltheryuujin** [comment]
Issues with a lesson in the curriculum should be opened on the appropriate repository in `learn-co-curriculum`.

When submitting a PR, the `learn-co-curriculum` repositories are reserved for proposed edits and improvements to the curriculum that will update across all forks.

We have integrated the updated the materials and believe your issue to have been resolved.
Thanks for contributing! 💙
